### ISSUE TITLE
Add license text?

### ISSUE THREAD

**Issue by ScatteredRay** [osen/FL_Flex#4]
Hi!

I was looking at using FL_Flex, seems like good and simple code and quite useful!

It doesn't seem to have a license applied, would you consider applying a license perhaps applying the same FLTK license would be appropriate?

https://github.com/fltk/fltk/blob/master/COPYING

**Comment by osen** [comment]
Hi there,

The project was fairly simple so I hadn't added a license up until now. However, agreed, this information could be important to anyone using it as a basis for their own work.

So going by your suggestion I have added the same license as upstream FLTK to the project. :)

**Comment by ScatteredRay** [comment]
Awesome! thanks!
